version: '3'
services:
  oracle:
    build:
      dockerfile: Dockerfile
      context: './oracle'
    container_name: oracle
    volumes:
      - './oracle:/usr/src/app' 
    ports:
      - 8080:8080
    expose:
      - "8080"
  ganache:
    image: 'trufflesuite/ganache-cli'
    container_name: 'ganache'
    ports:
      - 8545:8545
    expose:
      - "8545"
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data
        
volumes:
  database: